version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb-praise
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
