version: '3.8'
services:
  mongodb:
    container_name: mongodb-praise
    image: mongo:5.0.6
    env_file:
      - .env
    ports:
      - $MONGO_PORT:27017
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - './packages/mongodb/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro'
      - './packages/mongodb/entrypoint.sh:/entrypoint.sh:ro'
    entrypoint: /entrypoint.sh

  api:
    container_name: api-praise
    image: api
    env_file:
      - .env
    build:
      context: ./
      dockerfile: packages/api/Dockerfile
    restart: always
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - './packages/api/uploads/:/usr/src/uploads/'
      - './packages/api/exports/:/usr/src/exports/'
    links:
      - mongodb

  discord-bot:
    container_name: discord-bot-praise
    image: discord-bot
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./packages/discord-bot/Dockerfile
    restart: always
    links:
      - mongodb
      
  frontend:
    container_name: frontend-praise
    image: frontend
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./packages/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    links:
      - api

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
