version: '3.8'
services:
  mongodb:
    extends:
      file: packages/mongodb/docker-compose.yml
      service: mongodb
  
  api:
    container_name: api-praise
    image: api
    build: 
      context: ./
      dockerfile: ./packages/api/Dockerfile
    restart: always
    ports:
      - 8088:8088
    links:
      - mongodb

  discord-bot:
    container_name: discord-bot-praise
    image: discord-bot
    build: 
      context: ./
      dockerfile: ./packages/discord-bot/Dockerfile
    restart: always
    links:
      - mongodb

  frontend:
    container_name: frontend-praise
    image: frontend
    build: 
      context: ./
      dockerfile: ./packages/frontend/Dockerfile
      args:
        SERVER: $SERVER
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    links:
      - api

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
