version: '3.8'
services:
  mongodb:
    container_name: mongodb-praise
    image: mongo
    ports:
      - $MONGO_PORT:$MONGO_PORT
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - './users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD

volumes:
  mongodb_data:
