name: api
on:
  pull_request:
    paths:
      - 'packages/api/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Api - Build, Lint & Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace api lint
      - run: yarn workspace api build
      - run: echo "${{secrets.ROOT_ENV_TESTING }}" > .env
      - run: echo "${{secrets.API_ENV_TESTING }}" > packages/api/.env
      - run: yarn mongodb:start
      - run: yarn workspace api test