name: main
on: [pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    env:
      PORT=8088
      HOST=localhost
      SERVER_URL=http://localhost:8088
      FRONTEND_URL=http://localhost:3000
      MONGO_DB=praise_db
      MONGO_HOST=localhost
      MONGO_PORT=27017
      MONGO_USERNAME=user
      MONGO_PASSWORD=password
      COOKIE_DOMAIN=localhost
      COOKIE_PATH=/
      SECURE_COOKIE=false
      JWT_SECRET=xxxxxxxxxxxxxx
      COOKIE_SECRET=xxxxxxxxxxxxxx
      JWT_ACCESS_EXP=3600
      JWT_REFRESH_EXP=25920000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace api lint
      - run: yarn workspace api build
      - run: yarn workspace frontend lint
      - run: yarn workspace frontend build
      - run: yarn workspace discord-bot lint
      - run: yarn workspace discord-bot build
      - run: yarn mongodb:start
        env:
          First_Name: Mona
      - run: yarn workspace api test