name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace api build
      - run: yarn workspace api lint
      - run: yarn workspace frontend lint
      - run: yarn workspace discord-bot lint
