name: Api/Release - Create and publish Docker image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: praise/api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push Docker image
        with:
          image: $IMAGE_NAME
          tags: latest,${{ steps.docker-tag.outputs.tag }}
          addTimestamp: true
          registry: ghcr.io
          dockerfile: packages/api/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
