name: Development - Create and publish frontend Docker image

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: praise-dev/frontend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:    
      - uses: martinbeentjes/npm-get-version-action@main
        name: get-npm-version
        id: package-version
        with:
          path: packages/frontend
    
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push Docker image
        env:
          REACT_APP_VERSION: ${{ steps.package-version.outputs.current-version}}
        with:
          image: $IMAGE_NAME
          tags: latest
          addTimestamp: true
          registry: ghcr.io
          dockerfile: packages/frontend/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
